services:
  stage-postgres:
    container_name: stage-postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      - POSTGRES_DB=${POSTGRES_DB}
    expose:
      - 5432
    volumes:
      - stagedb:/var/lib/postgresql
    restart: always
  stage-prisma-postgres-api:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: stage-prisma-postgres-api
    depends_on:
      - stage-postgres
    ports:
      - "3000:3000"
    restart: always
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PW}@stage-postgres:5432/${POSTGRES_DB}?schema=sample
      - DEBUG=${DEBUG}
    command: npm run migratedeploy
volumes:
  stagedb: