services:
  dev-postgres:
    container_name: dev-postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - devdb:/var/lib/postgresql
    restart: always
  dev-prisma-postgres-api:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./server:/usr/src/app/server
      - ./nodemon.json:/usr/src/app/nodemon.json
      - ./prisma:/usr/src/app/prisma
    container_name: dev-prisma-postgres-api
    depends_on:
      - dev-postgres
    ports:
      - "3000:3000"
    restart: always
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PW}@dev-postgres:5432/${POSTGRES_DB}?schema=sample
      - DEBUG=${DEBUG}
    command: npm run dev
volumes:
  devdb: